### ISSUE TITLE
KeyError: ('Release', 'x64') in self.flags[context.current_setting][flag_name] = {}  # reset default values

### ISSUE THREAD

**Issue by taigacon** [pavelliavonau/cmakeconverter#109]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "c:\users\abc\appdata\local\programs\python\python37\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "c:\users\abc\appdata\local\programs\python\python37\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "c:\users\abc\appdata\local\programs\python\python37\lib\site-packages\cmake_converter\data_converter.py", line 278, in run_conversion
    project_data['subdirectory'],
  File "c:\users\abc\appdata\local\programs\python\python37\lib\site-packages\cmake_converter\data_converter.py", line 245, in convert_project
    self.collect_data(context)
  File "c:\users\abc\appdata\local\programs\python\python37\lib\site-packages\cmake_converter\data_converter.py", line 54, in collect_data
    context.parser.parse(context)
  File "c:\users\abc\appdata\local\programs\python\python37\lib\site-packages\cmake_converter\visual_studio\vcxproj\parser.py", line 140, in parse
    self._parse_nodes(context, root)
  File "c:\users\abc\appdata\local\programs\python\python37\lib\site-packages\cmake_converter\parser.py", line 86, in _parse_nodes
    node_handlers[child_node_tag](context, child_node)
  File "c:\users\abc\appdata\local\programs\python\python37\lib\site-packages\cmake_converter\visual_studio\vcxproj\parser.py", line 148, in __parse_item_group
    self._parse_nodes(context, node)
  File "c:\users\abc\appdata\local\programs\python\python37\lib\site-packages\cmake_converter\parser.py", line 80, in _parse_nodes
    self._parse_attributes(context, child_node)
  File "c:\users\abc\appdata\local\programs\python\python37\lib\site-packages\cmake_converter\parser.py", line 100, in _parse_attributes
    attributes_handlers[node_key](context, node_key, node.get(attr), node)
  File "c:\users\abc\appdata\local\programs\python\python37\lib\site-packages\cmake_converter\visual_studio\vcxproj\parser.py", line 206, in __parse_cl_compile_include_attr
    self.__parse_file_nodes(context, context.sources, cl_node, 'Sources')
  File "c:\users\abc\appdata\local\programs\python\python37\lib\site-packages\cmake_converter\visual_studio\vcxproj\parser.py", line 233, in __parse_file_nodes
    self._parse_nodes(file_context, file_node)
  File "c:\users\abc\appdata\local\programs\python\python37\lib\site-packages\cmake_converter\parser.py", line 86, in _parse_nodes
    node_handlers[child_node_tag](context, child_node)
  File "c:\users\abc\appdata\local\programs\python\python37\lib\site-packages\cmake_converter\visual_studio\vcxproj\flags.py", line 289, in set_flag
    self.flags[context.current_setting][flag_name] = {}  # reset default values
KeyError: ('Release', 'x64')
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\abc\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\abc\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\abc\AppData\Local\Programs\Python\Python37\Scripts\cmake-converter.exe\__main__.py", line 9, in <module>
  File "c:\users\abc\appdata\local\programs\python\python37\lib\site-packages\cmake_converter\main.py", line 126, in main
    converter.convert_solution(root_context, os.path.abspath(args.solution))
  File "c:\users\abc\appdata\local\programs\python\python37\lib\site-packages\cmake_converter\visual_studio\solution.py", line 281, in convert_solution
    results = self.do_conversion(root_context, input_data_for_converter)
  File "c:\users\abc\appdata\local\programs\python\python37\lib\site-packages\cmake_converter\data_converter.py", line 307, in do_conversion
    results = pool.map(self.run_conversion, input_converter_data_list)
  File "c:\users\abc\appdata\local\programs\python\python37\lib\multiprocessing\pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "c:\users\abc\appdata\local\programs\python\python37\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
KeyError: ('Release', 'x64')

**Comment by pavelliavonau** [comment]
@taigacon , so what?
Where is any analyze from you? check previous similar issues. A least verbose log of conversion.
it's just a possution of issue tracker.

**Comment by taigacon** [comment]
Okay, it's maybe a duplicated issue of #108.
The solution file and logs are attached below.

[solution.zip](https://github.com/pavelliavonau/cmakeconverter/files/4656919/solution.zip)

**Comment by pavelliavonau** [comment]
Are you also using premake to get generated solution?

**Comment by taigacon** [comment]
No, it's a native-created VS2019 project.
