### ISSUE TITLE
Exception when node.text is NoneType in visual_studio\vcxproj\dependencies.py, line 125

### ISSUE THREAD

**Issue by bigla** [pavelliavonau/cmakeconverter#80]
Hello friendly developers,

I have troubles pinpointing the exact vcxproj/sln causing the error attached when running: 
`%LOCALAPPDATA%\Programs\Python\Python37\Lib\site-packages\cmake_converter\main.py -v -s somesolution.sln > somesolution.sln_conversion_log 2>&1` (on windows)

I fixed this for myself by adding:
`if node.text is not None:`
before the line of
`list_ingore_spec_libs = node.text.replace('%(IgnoreSpecificDefaultLibraries)', '')`
in `cmake_converter\visual_studio\vcxproj\dependencies.py`

and indenting everything below it.

```
25.324834 240> Conversion done   : Project SOME_PROJECT (50 warnings)
25.324834 240> INFO : ------ Exiting  240 -------
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "%LOCALAPPDATA%\Programs\Python\Python37\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "%LOCALAPPDATA%\Programs\Python\Python37\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "%LOCALAPPDATA%\Programs\Python\Python37\lib\site-packages\cmake_converter\visual_studio\solution.py", line 45, in run_conversion
    project_data['subdirectory'],
  File "%LOCALAPPDATA%\Programs\Python\Python37\lib\site-packages\cmake_converter\visual_studio\solution.py", line 238, in convert_project
    data_converter.convert(context)
  File "%LOCALAPPDATA%\Programs\Python\Python37\lib\site-packages\cmake_converter\data_converter.py", line 198, in convert
    self.collect_data(context)
  File "%LOCALAPPDATA%\Programs\Python\Python37\lib\site-packages\cmake_converter\data_converter.py", line 50, in collect_data
    context.parser.parse(context)
  File "%LOCALAPPDATA%\Programs\Python\Python37\lib\site-packages\cmake_converter\visual_studio\vcxproj\parser.py", line 132, in parse
    self._parse_nodes(context, root)
  File "%LOCALAPPDATA%\Programs\Python\Python37\lib\site-packages\cmake_converter\parser.py", line 75, in _parse_nodes
    node_handlers[child_node_tag](context, child_node)
  File "%LOCALAPPDATA%\Programs\Python\Python37\lib\site-packages\cmake_converter\visual_studio\vcxproj\parser.py", line 172, in __parse_item_definition_group
    self._parse_nodes(context, node)
  File "%LOCALAPPDATA%\Programs\Python\Python37\lib\site-packages\cmake_converter\parser.py", line 75, in _parse_nodes
    node_handlers[child_node_tag](context, child_node)
  File "%LOCALAPPDATA%\Programs\Python\Python37\lib\site-packages\cmake_converter\parser.py", line 75, in _parse_nodes
    node_handlers[child_node_tag](context, child_node)
  File "%LOCALAPPDATA%\Programs\Python\Python37\lib\site-packages\cmake_converter\visual_studio\vcxproj\dependencies.py", line 125, in set_target_ignore_specific_default_libraries
    list_ingore_spec_libs = node.text.replace('%(IgnoreSpecificDefaultLibraries)', '')
AttributeError: 'NoneType' object has no attribute 'replace'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "%LOCALAPPDATA%\Programs\Python\Python37\Lib\site-packages\cmake_converter\main.py", line 129, in <module>
    main()
  File "%LOCALAPPDATA%\Programs\Python\Python37\Lib\site-packages\cmake_converter\main.py", line 125, in main
    convert_solution(initial_context, os.path.abspath(args.solution))
  File "%LOCALAPPDATA%\Programs\Python\Python37\lib\site-packages\cmake_converter\visual_studio\solution.py", line 312, in convert_solution
    results = __do_conversion(initial_context, input_data_for_converter)
  File "%LOCALAPPDATA%\Programs\Python\Python37\lib\site-packages\cmake_converter\visual_studio\solution.py", line 418, in __do_conversion
    results = pool.map(run_conversion, input_converter_data_list)
  File "%LOCALAPPDATA%\Programs\Python\Python37\lib\multiprocessing\pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "%LOCALAPPDATA%\Programs\Python\Python37\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by pavelliavonau** [comment]
Did you edited .vcxproj manually?
your case is 
`<IgnoreSpecificDefaultLibraries></IgnoreSpecificDefaultLibraries`, right?
But if you edit from UI - vs does:
`      <IgnoreSpecificDefaultLibraries>
      </IgnoreSpecificDefaultLibraries>`

**Comment by bigla** [comment]
I cannot exclude the possibility of someone in the history of the code I am working with changing anything manually (but I really, really doubt it), but I assume both of the following possibilities are "valid XML" and/or could lead to the missing space which I assume you referred to in your comment.

So i grepped over the *.vcxproj files and found mainly two (possibly) empty versions of ```<IgnoreSpecificDefaultLibraries>``` :

* ```<IgnoreSpecificDefaultLibraries />```
* ```<IgnoreSpecificDefaultLibraries>%(IgnoreSpecificDefaultLibraries)</IgnoreSpecificDefaultLibraries>```

and I strongly believe it is the latter case that is causing problems.
