### ISSUE TITLE
Crash on checking version of solution.

### ISSUE THREAD

**Issue by simonrenger** [pavelliavonau/cmakeconverter#95]
I am running to the following issue:

```
0.000059 processes count = 8
0.000508 warnings level = 2
Traceback (most recent call last):
  File "/usr/local/bin/cmake-converter", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/cmake_converter/main.py", line 126, in main
    converter.convert_solution(root_context, os.path.abspath(args.solution))
  File "/usr/local/lib/python3.7/dist-packages/cmake_converter/visual_studio/solution.py", line 266, in convert_solution
    solution_data = self.parse_solution(root_context, sln.read())
  File "/usr/local/lib/python3.7/dist-packages/cmake_converter/visual_studio/solution.py", line 56, in parse_solution
    self.__check_solution_version(root_context, sln_text)
  File "/usr/local/lib/python3.7/dist-packages/cmake_converter/visual_studio/solution.py", line 93, in __check_solution_version
    .format(version_match[0]), 'error')
IndexError: list index out of range
```

**Comment by pavelliavonau** [comment]
Provide sln file

**Comment by simonrenger** [comment]
@pavelliavonau I fixed it, myself my sln file was broken. I noticed too late. I cannot share the sln file because it contains information under NDA.
